### ISSUE TITLE
Generic types in Maps and List types are not transformed

### ISSUE THREAD

**Issue by misino** [havardh/javaflow#48]
When field type contains generic, the generic type is not transformed to the corresponding type.
For example, expected transformation of `Map<String, List<Integer>> field;` is `{[key: string]: Array<number>`

Actual result is wrong `{[key: string]: List<Integer>}`

Created also a failing test for it in this pull request: https://github.com/havardh/javaflow/pull/47

I am not sure how to solve it. Probably we will need to use some recursion and extract type from the string literal in TypeFactory.

**Comment by havardh** [comment]
Yes.

The problem here lies in the internal Map and List types. Their member types are too naive. And they do not supported nested generics. 

I think the solution could be to:

1. Change Map, and List to contain `Type` instead of `CanonicalName`. 
2. Make the `TypeWriter` recur back to `write(Type, Writer) for the keys and values.

e.g. for Map
```
  private void write(Map map, java.io.Writer writer) throws IOException {
    writer.write("{[key: ");
-   writer.write(converter.convert(map.getKeyType()));
+   write(map.getKeyType(), writer);
    writer.write("]: ");
-   writer.write(converter.convert(map.getValueType()));
+   write(map.getValueType(), writer);
    writer.write("}");
  }
```
This would make all the recursion end up in the call to the `converter` in the `write(Type, Wirter)` method.

3. Rewrite the type literal parser to recursively unfold nested generics in `TypeFactory.build`. Specifically `extractKeyType` and `extractValueType` methods for Map and `extractType` for List. 

What do you think?
